### ISSUE TITLE
Expose `march_edges` function

### ISSUE THREAD

**Issue by HeavyBro1337** [shnewto/bevy_collider_gen#8]
Hello, I wanted to say that the library is awesome! But I'd like to extend the flexibility of the library by exposing `march_edges` function, so we can have custom behavior rather than having only images to generate collisions from.

**Comment by shnewto** [comment]
hey thank you @IvanKorchmit! yeah I'm happy to expose the march_edges function if it'd be useful. if you're interested in making that PR please do! Otherwise I'll try and make the update this evening 😄

**Comment by shnewto** [comment]
@IvanKorchmit thanks for creating this issue! I'll publish this change to crates io shortly, let me know if you  bump into any issues

**Comment by shnewto** [comment]
okay, published to crates io 😄
